(() => {
  const RESOURCE = typeof GetParentResourceName === 'function' ? GetParentResourceName() : 'st_dealership';
  const state = { ctx:null, inventory:[], view:'showroom', current:null, trade:null };
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  async function nui(action,data={}){try{const r=await fetch(`https://${RESOURCE}/${action}`,{method:'POST',headers:{'Content-Type':'application/json; charset=UTF-8'},body:JSON.stringify(data)});return await r.json()}catch(_){return null}}
  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
  function money(v){return `${state.ctx?.currencySymbol||'$'}${Math.round(Number(v)||0).toLocaleString('en-US')}`}
  function title(v){return String(v||'').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}
  function conditions(v){if(!v)return{};if(typeof v==='object')return v;try{return JSON.parse(v)}catch(_){return{}}}
  function avgCondition(v){const vals=Object.values(conditions(v.condition_json)).map(Number);return vals.length?Math.round(vals.reduce((a,b)=>a+b,0)/vals.length):100}
  function photo(v){try{const p=typeof v.photos_json==='string'?JSON.parse(v.photos_json):v.photos_json;return Array.isArray(p)?p[0]:null}catch(_){return null}}
  function notify(h,b='',type='info'){const e=document.createElement('div');e.className=`toast ${type}`;e.innerHTML=`<b>${esc(h)}</b><span>${esc(b)}</span>`;$('#toasts').appendChild(e);setTimeout(()=>e.remove(),4200)}
  function applyTheme(theme={}){Object.entries(theme).forEach(([k,v])=>{if(typeof v==='string')document.documentElement.style.setProperty(`--${k.replace(/[A-Z]/g,m=>'-'+m.toLowerCase())}`,v)})}
  function perms(){return state.ctx?.permissions||{}} function can(k){return!!perms()[k]||!!perms().all} function isStaff(){return Object.entries(perms()).some(([k,v])=>k!=='all'&&v)} function isManager(){return can('hire')||can('manage_loans')||can('manage_finances')||can('approve_financing')} function isOwner(){return!!perms().all||can('configure_dealership')}
  window.addEventListener('message',e=>{const{action,data}=e.data||{};if(action==='open')open(data);if(action==='close')close();if(action==='placementResult')handlePlacement(data)});
  document.addEventListener('keydown',e=>{if(e.key==='Escape'){nui('close');close()}});
  function open(data){state.ctx=data;$('#app').classList.remove('hidden');$('#brand-name').textContent=data.dealership.label;$('#brand-type').textContent=title(data.dealership.type).toUpperCase();$('#brand-mark').textContent=(data.dealership.label||'D')[0];$('#role-label').textContent=isOwner()?'OWNER':isManager()?'MANAGEMENT':isStaff()?'EMPLOYEE':'CUSTOMER';$('#balance').classList.toggle('hidden',!isStaff());$('#balance').textContent=money(data.dealership.balance);$$('.staff-only').forEach(e=>e.classList.toggle('hidden',!isStaff()));$$('.manager-only').forEach(e=>e.classList.toggle('hidden',!isManager()));$$('.owner-only').forEach(e=>e.classList.toggle('hidden',!isOwner()));applyTheme(data.theme||data.branding?.theme||{});fillTerms();switchView(data.initialView||'showroom')}
  function close(){$('#app').classList.add('hidden');$('#modal').classList.add('hidden')} $('#close-btn').onclick=()=>{nui('close');close()};
  $$('.nav-item').forEach(b=>b.onclick=()=>switchView(b.dataset.view));
  function switchView(view){state.view=view;$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$$('.view').forEach(v=>v.classList.add('hidden'));$(`#view-${view}`).classList.remove('hidden');$('#page-title').textContent={showroom:'Showroom',tradein:'Trade-In',financing:'Financing',dealership:'Dealership',management:'Management',settings:'Settings'}[view]||'Showroom';if(view==='showroom')loadInventory();if(view==='financing')loadFinance();if(view==='dealership')loadDealership();if(view==='management')loadManagement();if(view==='settings')loadSettings()}
  async function loadInventory(){state.inventory=await nui('getInventory')||[];$('#inventory-count').textContent=state.inventory.length;$('#m-stock').textContent=state.inventory.length;renderInventory()}
  $('#search').oninput=renderInventory;$('#sort').onchange=renderInventory;
  function renderInventory(){const q=($('#search').value||'').toLowerCase();let list=state.inventory.filter(v=>String(v.model).toLowerCase().includes(q)||String(v.vin).toLowerCase().includes(q));const s=$('#sort').value;list.sort((a,b)=>s==='price_asc'?a.asking_price-b.asking_price:s==='price_desc'?b.asking_price-a.asking_price:s==='mileage_asc'?a.mileage-b.mileage:avgCondition(b)-avgCondition(a));$('#inventory-grid').innerHTML=list.map(card).join('');$('#empty').classList.toggle('hidden',list.length!==0);$$('.vehicle-card').forEach(e=>e.onclick=()=>openVehicle(e.dataset.vin))}
  function card(v){const p=photo(v),c=avgCondition(v);return `<article class="vehicle-card" data-vin="${esc(v.vin)}"><div class="vehicle-image">${p?`<img src="${esc(p)}" alt="">`:`<div class="image-fallback">${esc((v.model||'CAR').slice(0,2).toUpperCase())}</div>`}<span class="tag">${c>=85?'EXCELLENT':c>=70?'GOOD':'INSPECTED'}</span></div><div class="vehicle-info"><div><small>${esc(v.vin)}</small><h3>${esc(title(v.model))}</h3></div><strong>${money(v.asking_price)}</strong></div><div class="vehicle-meta"><span>${Number(v.mileage||0).toLocaleString()} mi</span><span>${c}% condition</span><span>${esc(title(v.title_status||'clean'))}</span></div></article>`}
  async function openVehicle(vin){const v=await nui('getVehicle',{vin});if(!v)return;state.current=v;showModal(vehicleModal(v))}
  function vehicleModal(v){const p=photo(v),c=avgCondition(v),parts=Object.entries(conditions(v.condition_json)).map(([k,val])=>`<div class="part"><span>${esc(title(k))}</span><div><i style="width:${Math.max(0,Math.min(100,Number(val)))}%"></i></div><b>${Number(val)}%</b></div>`).join('');return `<div class="modal-header"><div><div class="eyebrow">VEHICLE PROFILE</div><h2>${esc(title(v.model))}</h2><p>${esc(v.vin)}</p></div><button class="icon-btn" onclick="window.closeModal()">×</button></div>${p?`<img class="modal-photo" src="${esc(p)}" alt="">`:''}<div class="specs"><div><span>Asking price</span><b>${money(v.asking_price)}</b></div><div><span>Mileage</span><b>${Number(v.mileage||0).toLocaleString()} mi</b></div><div><span>Condition</span><b>${c}%</b></div><div><span>Title</span><b>${esc(title(v.title_status||'clean'))}</b></div></div><div class="modal-section"><div class="card-kicker">INSPECTION</div>${parts||'<p class="muted">No detailed condition report is stored.</p>'}</div><div class="actions"><button class="btn" id="inspect-btn">Run inspection</button><button class="btn" id="test-btn">Test drive</button><button class="btn" id="offer-btn">Negotiate</button><button class="btn primary" id="buy-btn">Purchase</button></div>${can('set_pricing')?`<div class="admin-box"><div class="card-kicker">INVENTORY</div><div class="row"><input id="price-input" type="number" value="${Number(v.asking_price)}"><button class="btn" id="price-save">Update price</button></div><div class="row"><input id="photo-url" placeholder="Vehicle image URL" value="${esc(p||'')}"><button class="btn" id="photo-save">Save photo</button><button class="btn ghost" id="photo-clear">Clear</button></div></div>`:''}${can('sell')?`<div class="admin-box"><div class="card-kicker">EMPLOYEE SALE</div><div class="row"><input id="buyer-id" placeholder="Buyer citizen ID"><input id="sale-price" type="number" value="${Number(v.asking_price)}"><button class="btn primary" id="employee-sale">Close sale</button></div></div>`:''}`}
  window.closeModal=()=>$('#modal').classList.add('hidden');function showModal(html){$('#modal-card').innerHTML=html;$('#modal').classList.remove('hidden');$('#modal').onclick=e=>{if(e.target.classList.contains('modal-backdrop'))window.closeModal()};bindVehicleModal()}
  function bindVehicleModal(){const v=state.current;const inspect=$('#inspect-btn');if(inspect)inspect.onclick=async()=>{const r=await nui('inspectVehicle',{vin:v.vin});if(r?.ok){notify('Inspection complete','Condition report updated.','success');window.closeModal();openVehicle(v.vin)}else notify('Inspection failed',r?.result||'Unable to inspect.','error')};const test=$('#test-btn');if(test)test.onclick=async()=>{await nui('startTestDrive',{vin:v.vin});window.closeModal();close()};const offer=$('#offer-btn');if(offer)offer.onclick=()=>negotiation(v);const buy=$('#buy-btn');if(buy)buy.onclick=()=>purchase(v,Number(v.asking_price));const ps=$('#price-save');if(ps)ps.onclick=async()=>{const r=await nui('adjustPrice',{vin:v.vin,price:Number($('#price-input').value)});if(r?.ok){notify('Price updated','Inventory price changed.','success');window.closeModal();loadInventory()}else notify('Price update failed',r?.result||'Unable to update.','error')};const ph=$('#photo-save');if(ph)ph.onclick=async()=>{const r=await nui('setVehiclePhoto',{vin:v.vin,url:$('#photo-url').value});if(r?.ok){notify('Photo saved','The vehicle preview now uses the supplied image URL.','success');window.closeModal();loadInventory()}else notify('Photo failed',r?.result||'Use a valid http(s) image URL.','error')};const pc=$('#photo-clear');if(pc)pc.onclick=async()=>{const r=await nui('clearVehiclePhoto',{vin:v.vin});if(r?.ok){notify('Photo removed');window.closeModal();loadInventory()}};const es=$('#employee-sale');if(es)es.onclick=async()=>{const r=await nui('employeeSell',{vin:v.vin,buyerCitizenId:$('#buyer-id').value,finalPrice:Number($('#sale-price').value),dealOptions:{financed:false}});if(r?.ok){notify('Sale completed','Commission has been processed.','success');window.closeModal();loadInventory()}else notify('Sale failed',r?.result||'Unable to close sale.','error')}}
  function negotiation(v){showModal(`<div class="modal-header"><div><div class="eyebrow">NEGOTIATION</div><h2>${esc(title(v.model))}</h2><p>Asking ${money(v.asking_price)} · Floor ${money(v.min_price)}</p></div><button class="icon-btn" onclick="window.closeModal()">×</button></div><label>Your offer<input id="offer-value" type="number" value="${Number(v.asking_price)}"></label><button class="btn primary block" id="evaluate">Evaluate offer</button><div id="offer-result" class="result"></div>`);$('#evaluate').onclick=async()=>{const r=await nui('evaluateOffer',{vin:v.vin,offer:Number($('#offer-value').value)});if(!r)return;$('#offer-result').innerHTML=`<b>${esc(title(r.verdict))}</b><span>${r.counter?`Counter: ${money(r.counter)}`:''}</span>`;if(r.verdict==='accept'){const b=document.createElement('button');b.className='btn primary block';b.textContent='Purchase at this price';b.onclick=()=>purchase(v,Number($('#offer-value').value));$('#offer-result').appendChild(b)}else if(r.counter)$('#offer-value').value=Math.round(r.counter)}}
  function purchase(v,price){showModal(`<div class="modal-header"><div><div class="eyebrow">PURCHASE</div><h2>${esc(title(v.model))}</h2><p>${money(price)} final price</p></div><button class="icon-btn" onclick="window.closeModal()">×</button></div><div class="purchase-grid"><button class="choice active" data-mode="cash">CASH / BANK</button><button class="choice" data-mode="finance">FINANCE</button></div><div id="purchase-body"></div>`);let mode='cash';$$('.choice').forEach(b=>b.onclick=()=>{$$('.choice').forEach(x=>x.classList.remove('active'));b.classList.add('active');mode=b.dataset.mode;renderPurchase()});function renderPurchase(){if(mode==='cash'){$('#purchase-body').innerHTML=`<p class="muted">Complete the purchase for ${money(price)}.</p><button class="btn primary block" id="complete">Complete purchase</button>`;$('#complete').onclick=()=>completePurchase({financed:false,downPayment:price,termMonths:0})}else{$('#purchase-body').innerHTML=`<label>Down payment<input id="down" type="number" min="0" value="0"></label><label>Term<select id="term"></select></label><button class="btn" id="quote-purchase">Quote loan</button><div id="purchase-quote" class="result"></div>`;fillTerms($('#term'));$('#quote-purchase').onclick=async()=>{const q=await nui('quoteFinancing',{price,downPayment:Number($('#down').value),termMonths:Number($('#term').value)});$('#purchase-quote').innerHTML=q?`<b>${q.approved?'Approved':'Declined'}</b><span>${q.reason||''} ${q.monthlyPayment?`Monthly: ${money(q.monthlyPayment)}`:''}</span>`:'';if(q?.approved){const b=document.createElement('button');b.className='btn primary block';b.textContent='Submit financing request';b.onclick=()=>completePurchase({financed:true,downPayment:Number($('#down').value),termMonths:Number($('#term').value)});$('#purchase-quote').appendChild(b)}}}}async function completePurchase(opts){const r=await nui('kioskPurchase',{vin:v.vin,finalPrice:price,dealOptions:opts});if(r?.ok){notify('Purchase complete','Your vehicle is being prepared.','success');window.closeModal();loadInventory()}else notify('Purchase failed',r?.result||'Unable to complete purchase.','error')}renderPurchase()}
  $('#appraise-btn').onclick=async()=>{const r=await nui('appraiseTradeIn');if(r?.error){notify('Trade-in unavailable','You must be inside the vehicle you want appraised.','error');return}state.trade=r;const amount=r?.offer?.offerAmount??r?.offerAmount??r?.value??0;$('#trade-result').classList.remove('hidden');$('#trade-result').innerHTML=`<b>Estimated offer: ${money(amount)}</b><span>${esc(r?.offer?.message||'Review the offer before accepting it.')}</span><button class="btn primary" id="accept-trade">Accept offer</button>`;$('#accept-trade').onclick=async()=>{const rr=await nui('acceptTradeIn',{offerId:r?.offer?.id||r?.offerId});if(rr?.ok){notify('Trade-in accepted','The vehicle has been added to dealership inventory.','success');$('#trade-result').classList.add('hidden')}}};
  function fillTerms(select=$('#finance-term')){if(!select)return;const terms=state.ctx?.financingTerms||{};const values=Array.isArray(terms)?terms:[36,48,60,72];select.innerHTML=values.map(v=>`<option value="${Number(v)}">${Number(v)} months</option>`).join('')}
  async function loadFinance(){fillTerms();if(isManager()){const[req,loans]=await Promise.all([nui('getFinancingRequests'),nui('getActiveLoans')]);renderRequests(req||[]);renderLoans(loans||[]);$('#m-requests').textContent=(req||[]).length;$('#m-loans').textContent=(loans||[]).length}}
  $('#quote-btn').onclick=async()=>{const q=await nui('quoteFinancing',{price:Number($('#finance-price').value),downPayment:Number($('#finance-down').value),termMonths:Number($('#finance-term').value)});$('#quote-result').classList.remove('hidden');$('#quote-result').innerHTML=q?`<b>${q.approved?'Approved':'Declined'}</b><span>${esc(q.reason||'')} ${q.apr?`APR ${q.apr}% · `:''}${q.monthlyPayment?`Monthly ${money(q.monthlyPayment)}`:''}</span>`:'No quote returned.'};
  function renderRequests(rows){$('#requests').innerHTML=rows.length?rows.map(r=>`<div class="list-row"><div><b>${esc(r.customer_name||r.buyer_citizenid||'Customer')}</b><span>${esc(r.model||r.vin||'Vehicle')} · ${money(r.final_price||r.price||0)}</span></div><div><button class="btn small" data-approve="${r.id}">Approve</button><button class="btn small danger" data-deny="${r.id}">Deny</button></div></div>`).join(''):'<p class="muted">No pending financing requests.</p>';$$('[data-approve]').forEach(b=>b.onclick=async()=>{const r=await nui('approveFinancingRequest',{requestId:b.dataset.approve});notify(r?.ok?'Approved':'Approval failed',r?.result||'',r?.ok?'success':'error');loadFinance()});$$('[data-deny]').forEach(b=>b.onclick=async()=>{const r=await nui('denyFinancingRequest',{requestId:b.dataset.deny});notify(r?.ok?'Denied':'Denial failed',r?.result||'',r?.ok?'info':'error');loadFinance()})}
  function renderLoans(rows){$('#loans').innerHTML=rows.length?rows.map(r=>`<tr><td>${esc(r.buyer_citizenid||r.customer||'Customer')}</td><td>${esc(r.model||r.vin||'Vehicle')}</td><td>${money(r.remaining_balance||r.balance||0)}</td><td>${money(r.monthly_payment||0)}</td><td>${r.missed_payments||0}</td><td>${esc(r.status||'active')}</td><td>${r.repo_eligible?`<button class="btn small" data-repo="${r.id}">Complete Repo</button>`:`<button class="btn small" data-ping="${r.id}">Locate</button>`}</td></tr>`).join(''):'<tr><td colspan="7" class="muted">No active loans.</td></tr>';$$('[data-ping]').forEach(b=>b.onclick=async()=>{const r=await nui('pingFinancedVehicle',{loanId:b.dataset.ping});notify(r?.ok?'Location updated':'Unable to locate',r?.result||'',r?.ok?'success':'error')});$$('[data-repo]').forEach(b=>b.onclick=async()=>{const r=await nui('completeRepo',{loanId:b.dataset.repo});notify(r?.ok?'Repossession completed':'Repo failed',r?.result||'',r?.ok?'success':'error');loadFinance()})}
  async function loadDealership(){await loadInventory();renderOpsInventory();loadStaff();loadDisplay();loadAuctions();$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.tab-panel').forEach(x=>x.classList.add('hidden'));$(`#tab-${b.dataset.tab}`).classList.remove('hidden')})}
  function renderOpsInventory(){$('#tab-inventory').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Vehicle</th><th>VIN</th><th>Price</th><th>Condition</th><th>Photo</th><th></th></tr></thead><tbody>${state.inventory.map(v=>`<tr><td>${esc(title(v.model))}</td><td>${esc(v.vin)}</td><td>${money(v.asking_price)}</td><td>${avgCondition(v)}%</td><td>${photo(v)?'Set':'None'}</td><td><button class="btn small" data-edit="${esc(v.vin)}">Open</button></td></tr>`).join('')}</tbody></table></div>`;$$('[data-edit]').forEach(b=>b.onclick=()=>openVehicle(b.dataset.edit))}
  async function loadStaff(){if(!can('hire')&&!can('fire')){$('#tab-staff').innerHTML='<p class="muted">You do not have staff-management permission.</p>';return}const rows=await nui('getOnlineStaff')||[];$('#tab-staff').innerHTML=`<div class="card"><div class="card-kicker">HIRE STAFF</div><div class="row"><input id="hire-id" type="number" placeholder="Player server ID"><select id="hire-grade"></select><button class="btn primary" id="hire-btn">Hire</button></div></div><div class="table-wrap" style="margin-top:16px"><table><thead><tr><th>Employee</th><th>Grade</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.name||r.citizenid||'Employee')}</td><td>${esc(r.grade_label||r.grade||'')}</td><td>${can('fire')?`<button class="btn small danger" data-fire="${r.source||r.serverId||''}">Fire</button>`:''}</td></tr>`).join('')}</tbody></table></div>`;const grades=state.ctx?.staffGrades||[];$('#hire-grade').innerHTML=grades.map(g=>`<option value="${g.level}">${esc(g.label)}</option>`).join('');$('#hire-btn').onclick=async()=>{const r=await nui('hireStaff',{targetId:Number($('#hire-id').value),grade:Number($('#hire-grade').value)});notify(r?.ok?'Employee hired':'Hire failed',r?.result||'',r?.ok?'success':'error');loadStaff()};$$('[data-fire]').forEach(b=>b.onclick=async()=>{const r=await nui('fireStaff',{targetId:Number(b.dataset.fire)});notify(r?.ok?'Employee removed':'Fire failed',r?.result||'',r?.ok?'success':'error');loadStaff()})}
  async function loadDisplay(){const zones=await nui('getDisplayZones')||[];$('#tab-display').innerHTML=`<p class="muted">Assign vehicles to configured display slots. Selling an assigned vehicle clears its slot automatically.</p><div class="table-wrap"><table><thead><tr><th>Slot</th><th>Vehicle</th><th></th></tr></thead><tbody>${zones.map(z=>`<tr><td>${esc(z.label||z.id)}</td><td>${esc(z.model?title(z.model):'Empty')}</td><td><select data-display="${z.id}"><option value="">Clear</option>${state.inventory.map(v=>`<option value="${esc(v.vin)}" ${v.vin===z.vin?'selected':''}>${esc(title(v.model))} · ${esc(v.vin)}</option>`).join('')}</select></td></tr>`).join('')}</tbody></table></div>`;$$('[data-display]').forEach(s=>s.onchange=async()=>{const r=s.value?await nui('assignDisplayVehicle',{zoneId:s.dataset.display,vin:s.value}):await nui('clearDisplayVehicle',{zoneId:s.dataset.display});notify(r?.ok?'Display updated':'Update failed',r?.result||'',r?.ok?'success':'error')})}
  async function loadAuctions(){const rows=await nui('getOpenAuctions')||[];$('#tab-auctions').innerHTML=`<div class="grid-2">${rows.map(a=>`<div class="card"><div class="card-kicker">OPEN AUCTION</div><h3>${esc(title(a.model))}</h3><p class="muted">Current bid ${money(a.current_bid)} · ends ${esc(a.ends_at||'')}</p><div class="row"><input data-bid="${a.id}" type="number" placeholder="Bid"><button class="btn primary" data-bidbtn="${a.id}">Bid</button></div></div>`).join('')||'<p class="muted">No open auctions.</p>'}</div>`;$$('[data-bidbtn]').forEach(b=>b.onclick=async()=>{const r=await nui('placeBid',{auctionId:Number(b.dataset.bidbtn),amount:Number($(`[data-bid="${b.dataset.bidbtn}"]`).value)});notify(r?.ok?'Bid placed':'Bid failed',r?.result||'',r?.ok?'success':'error');loadAuctions()})}
  async function loadManagement(){await loadInventory();const[req,loans,leaders]=await Promise.all([nui('getFinancingRequests'),nui('getActiveLoans'),nui('getLeaderboard')]);$('#m-balance').textContent=money(state.ctx?.dealership?.balance);$('#m-stock').textContent=state.inventory.length;$('#m-requests').textContent=(req||[]).length;$('#m-loans').textContent=(loans||[]).length;$('#leaderboard').innerHTML=(leaders||[]).length?leaders.map((r,i)=>`<div class="list-row"><div><b>#${i+1} ${esc(r.citizenid)}</b><span>${r.vehicles_sold||0} vehicles · ${money(r.sales_volume||0)} volume</span></div><strong>${money(r.avg_deal||0)} avg.</strong></div>`).join(''):'<p class="muted">No employee sales have been recorded.</p>'}
  async function loadSettings(){const b=await nui('getBranding')||{};$('#set-label').value=b.label||state.ctx.dealership.label;const t={...(state.ctx.theme||{}),...(b.theme||{})};$('#set-primary').value=t.primary||'';$('#set-secondary').value=t.secondary||'';const types=state.ctx.zoneTypes||[];$('#zone-type').innerHTML=types.map(z=>`<option value="${z.key}">${esc(z.label)}</option>`).join('');renderZones(await nui('getZones')||[])}
  function renderZones(rows){$('#zones').innerHTML=rows.length?rows.map(z=>`<div class="list-row"><div><b>${esc(z.label||z.zone_type)}</b><span>${esc(z.shape||'point')}</span></div><button class="btn small danger" data-zone-delete="${z.id}">Delete</button></div>`).join(''):'<p class="muted">No custom zones configured.</p>';$$('[data-zone-delete]').forEach(b=>b.onclick=async()=>{const r=await nui('deleteZone',{id:Number(b.dataset.zoneDelete)});notify(r?.ok?'Zone deleted':'Delete failed',r?.result||'',r?.ok?'success':'error');renderZones(await nui('getZones')||[])})}
  $('#save-branding').onclick=async()=>{const r=await nui('updateBranding',{branding:{label:$('#set-label').value.trim(),theme:{primary:$('#set-primary').value.trim(),secondary:$('#set-secondary').value.trim()}}});if(r?.ok){state.ctx.theme={...(state.ctx.theme||{}),...r.result?.theme};applyTheme(state.ctx.theme);notify('Settings saved','Branding and theme updated.','success')}else notify('Save failed',r?.result||'','error')};
  $('#capture-zone').onclick=()=>nui('startZoneCapture',{zoneType:$('#zone-type').value});$('#capture-poly').onclick=()=>nui('startPolygonCapture',{zoneType:$('#zone-type').value});
  function handlePlacement(data){if(!data||data.kind!=='zone'||!data.placement)return;const zone={...data.placement,zone_type:data.zoneType,shape:data.placement.points?'poly':'point'};nui('createZone',{zone}).then(r=>{notify(r?.ok?'Zone created':'Zone failed',r?.result||'',r?.ok?'success':'error');loadSettings()})}
  loadInventory();
})();
